### ISSUE TITLE
Latest Update returning GBDeviceDisplayUnknown?

### ISSUE THREAD

**Issue by dxclancy** [lmirosevic/GBDeviceInfo#50]
I'm on the simulator, and I'm familiar with #41, and I looked briefly at the code which sets GBDeviceDisplayUnknown for the simulator, but I have an NSAssert firing on a return from [GBDeviceInfo deviceInfo].displayInfo.display when GBDeviceDisplayUnknown is returned that was not firing before.  It looks like you used to return a valid display for this value, even if it was generic? Or am I wrong about this? This is a breaking change if so.

**Comment by lmirosevic** [comment]
You're right... The display enum used to be calculated based on the logical dimensions of the screen (points). This created a problem with the new iPad Pro devices in two sizes because it made their screens indistinguishable. Between iPhone 5/5S/5C, it was still somewhat acceptable, but having an iPad Pro with a 9.7 inch and a 12.9 inch display returning the same value was definitely wrong.

But you're right that this is a breaking change. At least on the simulator--on real devices it's not. I'll restore the previous functionality as a patch release on 4.x, and make a major bump to 5.0.0 with the new functionality.

**Comment by lmirosevic** [comment]
I just realised that this *was* published as a major bump, from `3.8.0` to `4.0.0`.

**Comment by philipengberg** [comment]
Is this scheduled for release any time soom @lmirosevic?

**Comment by lmirosevic** [comment]
@philipengberg No need for a release. `3.8.0` returns screen info on the Simulator, but going forward this can't be done reliably (see comment above). And `4.0.0` has the new robust behaviour--but device only.
