### ISSUE TITLE
How can used it in  swift?

### ISSUE THREAD

**Issue by Spiderbezno** [lmirosevic/GBDeviceInfo#51]
How can used it in  swift?

**Comment by castus** [comment]
+1

**Comment by javierHolvi** [comment]
Some information on this? I get "**target has transitive dependencies that include static binaries**"
Using in the podfile:

 use_frameworks!
  pod 'GBDeviceInfo', '4.2.2'
  pod 'GBDeviceInfo/Jailbreak', '4.2.2'

**Comment by lmirosevic** [comment]
The Jailbreak detection is a statically compiled library that is closed-source, and this isn't supported with CocoaPods/Swift. If you use `use_frameworks!` then you'll have to drop the Jailbreak pod. The reason is to make reverse engineering more difficult.

I am open to suggestions on how to include a static closed-source library in a Swift project.

**Comment by zssr** [comment]
for jailbreak detection, check https://github.com/0dayZh/JailbrokenDetector
