### ISSUE TITLE
Build issue when integrated as static library

### ISSUE THREAD

**Issue by condemned77** [lmirosevic/GBDeviceInfo#64]
Hi there, 

I've build the GBDevice info library as a static library (iOS) via the attached Xcode project.
The resulting files look as follows:
<img width="247" alt="screen shot 2017-03-09 at 12 18 02" src="https://cloud.githubusercontent.com/assets/2405937/23748175/c27cb40c-04c2-11e7-98f8-9be570cce7df.png">

Since the header file GBDeviceInfo_iOS.h is the only header copied to the resulting folder, I receive a build error once I integrated the resulting folder into an Xcode project.
<img width="1321" alt="screen shot 2017-03-09 at 12 22 54" src="https://cloud.githubusercontent.com/assets/2405937/23748286/3c90e5a6-04c3-11e7-9da4-f82d44c8859a.png">

Am I using the resulting library in the wrong manner?
Is it fine to simply copy the necessary header into my project.
These would be:
GBDeviceInfo_Common.h
GBDeviceInfoTypes_Common.h
GBDeviceInfoInterface.h
GBDeviceInfoTypes_iOS.h
<img width="320" alt="screen shot 2017-03-09 at 12 27 21" src="https://cloud.githubusercontent.com/assets/2405937/23748413/d968418a-04c3-11e7-8a50-52f24746ade1.png">

**Comment by lmirosevic** [comment]
You could just copy all of the files that have `_common` and `_iOS` suffixes, both `.h` and `.m` files to your project. 

The project also uses a prefix header for the common imports, so you would need to copy those lines to your own project's .pch file in order to get it to compile.

I wouldn't recommend this approach though, as you loose the ability to easily update the library when new devices are released. I would suggest using CocoaPods to install it.
