### ISSUE TITLE
Move jailbreak detection in sub podspec

### ISSUE THREAD

**Issue by rist** [lmirosevic/GBDeviceInfo#71]
Hi

would it be possible to move the jailbreak detection (and therefore the dependency to GBJailbreakDetection) to a cocoapod subspec?

The reason is that our app needs to get reviewed and audited on a regular basis and having a closed source/compiled component in there adds some hassle for us. And we anyway need to do jailbreak detection but are forced to use another implementation.

What do you think about that change? I could try to create a PR for that.

**Comment by rist** [comment]
oh, forget it - I missed the fact that it's already in a subspec

**Comment by lmirosevic** [comment]
😝 

Out of interest, what other jailbreak implementation do you use?

**Comment by rist** [comment]
Currently we use DTTJailbreakDetection which is quite old and probably outdated mainly to get an idea how many of our customers are using jailbroken devices.
But I expect to be forced to include a malware/jailbreak detection package of some big security vendor in the near future.

**Comment by lmirosevic** [comment]
Interesting. Yeah the problem with open sourcing jailbreak detection is that it then makes it easy to reverse engineer. As soon as many people start relying on a single library then the attack dynamic changes and it becomes economically worthwhile to actually do so. It's a similar story with In App Purchase validation, so it's an accepted best practice to implement this yourself. As an interesting anecdote as soon as I released the jailbreak detection, almost immediately someone involved in the jailbreak/cydia community asked how it works (see #28).

Some considerable effort went into making the jailbreak detection hard to reverse engineer, with lots of runtime gymnastics. If in principle you'd like to use the library, and it's just the closed-sourced'ness that is an issue, I would be happy to consider licensing you the full source code so that you can fulfil your auditing requirements.
